[package]
name = "ver-stub-example-build"
version = "0.1.0"
edition = "2024"

[build-dependencies]
ver-stub-build = { path = "../ver-stub-build" }
ver-stub-example = { path = "../ver-stub-example", artifact = "bin" }
